### PR TITLE
Add stock U-Boot image for TP-Link TL-WR902AC v1

### PR DESCRIPTION
**Pull request by FreifunkUFO**
Upload an original uboot. even openwrt/lede on this device already:

root@LEDE:~# cat /etc/openwrt_*
DISTRIB_ID='LEDE'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r5117-fbde9ac'
DISTRIB_CODENAME='reboot'
DISTRIB_TARGET='ar71xx/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='LEDE Reboot SNAPSHOT r5117-fbde9ac'
DISTRIB_TAINTS=''
r5117-fbde9ac
root@LEDE:~# uname -a
Linux LEDE 4.4.93 #0 Thu Oct 19 14:14:19 2017 mips GNU/Linux
root@LEDE:~#

### CODE REVIEW

**Comment by FreifunkUFO** [comment]
pepe2k uboot mod already running at some of my devices of this kind. 
so this pullrequest is only for documentation. 

argh, i muddle my former detailed way to opkg install kmod-mtd-rw with snapshot image compilation, its outdated now.

**Comment by TnA-Plastic** [comment]
I would like to see that U-Boot-Version for the 'V3', if possible.

@FreifunkUFO: Greetings from Chemnitz! :)

**Comment by FreifunkUFO** [comment]
@TnA-Plastic ha, i saw that v3 at saturn.de shop lately. do you have it already?

**Comment by TnA-Plastic** [comment]
Yes, I have it since a few months already! :-)

I haven't installed OpenWRT yet, but I want to do that quite soon.
The Info-Page about OpenWRT on it still says 5GHz doesn't work, but it does, if you install something via LuCi.

**Comment by FreifunkUFO** [comment]
so do you have corresponding openwrt-ticket to support that device, or is it existing yet? maybe its almost the same as v1? or maybe they changed to mt7621 as on other devices. that would be great. 
do you have serial or maybe tplink disabled that onboard as on other devices?

**Comment by FreifunkUFO** [comment]
@TnA-Plastic : link to your regret: https://openwrt.org/toh/hwdata/tp-link/tp-link_tl-wr902ac_v3

**Comment by TnA-Plastic** [comment]
Yes, that's the model I have!
The only thing that's missing is the 'tuned' U-Boot! ;)

**Comment by CodeFetch** [comment]
Merged in my [fork](https://github.com/CodeFetch/router-u-boot/).

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.

**Pull request closed without merging**
