### PR TITLE
Routerboot Mikrotik mAP2n support

### PR DESCRIPTION
**Pull request by pawelkn**
I have added support for Routerboot Mikrotik mAP2n. I have added new makefile rules and information in README files.

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello Paweł,

I'm almost sure it won't work with Mikrotik RouterOS... have you tested it at all?

Cheers

**Comment by pawelkn** [comment]
Yes, It will not work with Mikrotik RouterOS. It is intended to run OpenWrt. I have tested it with OpenWrt. It works. The hardware of mAP2n is similar to the gl-inet device. The only difference is a reset switch, which is placed on pin 6 and is active low.

**Comment by pepe2k** [comment]
Are you able provide bootlog from the serial console?

Some other comments:
- include information somewhere in README that it will work only with OpenWrt and not with RouterOS
- fix manufacturer name in first commit message (Microtick -> Mikrotik)
- take a look at https://github.com/pepe2k/u-boot_mod/blob/master/u-boot/include/configs/ap121.h - are the default defines OK for this device?

**Comment by pawelkn** [comment]
Yes, I am able to provide a bootlog from serial console. [mAP2n-bootlog.txt](https://github.com/pepe2k/u-boot_mod/files/223260/mAP2n-bootlog.txt)

Ok, I will fix the README and misspells.

About *ap121.h*. 
I do not need to setup any GPIO, except the reset input which is already defined in the u-boot's makefile. What makes me confused, are default bootargs definitions. There are no "board=" property defined in any configuration. Why? It is necessary to provide this information to kernel. So the bootargs must be redefined by hand by serial console. So, should I care about default bootargs settings?

PS. I have noticed that the bootargs for GL.iNET board are wrong. The partition table has only 4MB allocated, but the router has 16MB flash.

**Comment by pepe2k** [comment]
Hello Paweł,

> About ap121.h.
> I do not need to setup any GPIO, except the reset input which is already defined in the u-boot's makefile.

As far as I see, this device has several LEDs controlled from GPIO and USB power also controlled from GPIO. So, you should define those output GPIOs. LEDs are ex. used for indication about web recovery mode.

> What makes me confused, are default bootargs definitions. There are no "board=" property defined in any configuration. Why? It is necessary to provide this information to kernel. So the bootargs must be redefined by hand by serial console. So, should I care about default bootargs settings?

For this target (ar71xx) OpenWrt uses static bootargs, embedded in kernel. Bootargs defined in ap121.h here are used only for stock firmware as it needs them.

> PS. I have noticed that the bootargs for GL.iNET board are wrong. The partition table has only 4MB allocated, but the router has 16MB flash.

As above, for OpenWrt it doesn't matter at all.

Piotr

**Comment by pepe2k** [comment]
Hello Paweł,

Are you going to work on this PR (LEDs GPIOs)?

Cheers,
Piotr

**Pull request closed without merging**
