### PR TITLE
Added zsun_sd support.

### PR DESCRIPTION
**Pull request by thornley-david**
Device's original uboot flash layout had kernel after rootfs and not allocated enough space for modern lede/openwrt kernel images, so this was changed to 128k(u-boot),64k(u-boot-env),16128k(firmware),64k(ART) with the kernel/rootfs being in firmware.
Added flash support for JEDEC EF6018 (W25Q128FW)
Minor fix (writting should be writing)

See - https://wiki.hackerspace.pl/projects:zsun-wifi-card-reader

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @landswipe,

Sorry for the delay. I will take a look at this soon.

Cheers,
Piotr

**Comment by landswipe** [comment]
No probs!! :) I also have some build improvements to the make file to
submit.. Will do that tomorrow :)

Thanks in advance.

**Comment by waschmi** [comment]
Will this Patch enable the Zsun to flash U-Boot over WiFi or USB (sdcard)? At least with the recent Generation the Ethernet pads are not functional and even Serial Console doesn't come easy.

**Comment by landswipe** [comment]
Nope unfortunately not, but it should enable upload over serial (ymodem or
kermit) which results in a lot less 'tricky' soldering :) I haven't tested
though I expect it to work.

**Comment by waschmi** [comment]
@landswipe
http://pastebin.com/ude6kHLW
I modifed your submission to apply to a u-boot source tree that support flash via USB ( https://github.com/unwireddevices/u-boot ) ... I'd like to say but my level of I-have-no-idea-what-I'm-doing is very high and couldn't complete it. This source also seems to rely on reset-button timing event to flash from USB _FW Folder. Not sure how to handle that with the zsun.

Maybe you or someone reading this is interested in making it work.
[zsun.txt](https://github.com/pepe2k/u-boot_mod/files/411884/zsun.txt)

**Comment by landswipe** [comment]
Sure I'll take a look!!! Thanks for sending the code, if you can, a pull
request is a better way to share your efforts via GitHub. :)

**Comment by vk496** [comment]
Sad this was not merged. Great work!

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.

**Pull request closed without merging**
