### PR TITLE
Add support for D-Link DIR-601 rev B1 (AR9331 based)

### PR DESCRIPTION
**Pull request by e-f-p**
Successfully flashed to my hardware to test and in preparation for performing NOR flash upgrade. 

https://pastebin.com/3TVpYe00

### CODE REVIEW

**Comment by pepe2k** [comment]
@e-f-p could you please include Signed-off-by line in your commit?

Cheers,
Piotr

**Comment by e-f-p** [comment]
Not sure why that merge was necessary.. oh well.

**Comment by pepe2k** [comment]
> Not sure why that merge was necessary.. oh well.

I have already merged your changes locally but I need your SoB with real name and e-mail, please.

Cheers,
Piotr

**Comment by pepe2k** [comment]
@e-f-p, ping.

**Pull request closed without merging**
